name: Build and Test

on:
  # Trigger the workflow on push to any branch except master
  # Trigger it for any pull request to master
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with dotnet
      run: dotnet build src --configuration Release
