name: Build and Test

on:
  # Trigger the workflow on push to any branch except master
  # Trigger it for any pull request to master
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with dotnet
      run: dotnet build src --configuration Release
      
  publish_prereleases:
  
    name: Publish prerelease nuget packages on master
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Build with dotnet and create prerelease nupkg
      run: dotnet build src --configuration PreRelease --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
      shell: bash
    - name: Publish nuget
      run: |
           sed -i -e 's/TOKEN/${{ secrets.GITHUB_TOKEN }}/g' ./.build/nuget.config
           cp ./.build/nuget.config ./nuget.config
           for f in ./src/Agents.Net/bin/PreRelease/*.nupkg
           do
             dotnet nuget push "$f" -s "github" --no-symbols --skip-duplicate
           done
      shell: bash